/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Segment = IDL.Record({
  'segmentId' : IDL.Nat,
  'text' : IDL.Text,
  'score' : IDL.Float64,
  'alternatives' : IDL.Vec(IDL.Text),
  'flagged' : IDL.Bool,
});
export const CheckResult = IDL.Record({
  'id' : IDL.Nat,
  'overallScore' : IDL.Float64,
  'segments' : IDL.Vec(Segment),
});
export const CheckSummary = IDL.Record({
  'id' : IDL.Nat,
  'overallScore' : IDL.Float64,
  'wordCount' : IDL.Nat,
  'preview' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'deleteCheck' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCheck' : IDL.Func([IDL.Nat], [IDL.Opt(CheckResult)], ['query']),
  'getHistory' : IDL.Func([], [IDL.Vec(CheckSummary)], ['query']),
  'submitCheck' : IDL.Func([IDL.Text], [CheckResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Segment = IDL.Record({
    'segmentId' : IDL.Nat,
    'text' : IDL.Text,
    'score' : IDL.Float64,
    'alternatives' : IDL.Vec(IDL.Text),
    'flagged' : IDL.Bool,
  });
  const CheckResult = IDL.Record({
    'id' : IDL.Nat,
    'overallScore' : IDL.Float64,
    'segments' : IDL.Vec(Segment),
  });
  const CheckSummary = IDL.Record({
    'id' : IDL.Nat,
    'overallScore' : IDL.Float64,
    'wordCount' : IDL.Nat,
    'preview' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'deleteCheck' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCheck' : IDL.Func([IDL.Nat], [IDL.Opt(CheckResult)], ['query']),
    'getHistory' : IDL.Func([], [IDL.Vec(CheckSummary)], ['query']),
    'submitCheck' : IDL.Func([IDL.Text], [CheckResult], []),
  });
};

export const init = ({ IDL }) => { return []; };