/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CheckRecord {
  'id' : bigint,
  'wordCount' : bigint,
  'mode' : string,
  'text' : string,
  'plagiarismScore' : number,
  'timestamp' : bigint,
  'aiScore' : number,
}
export interface Suggestion {
  'id' : bigint,
  'name' : [] | [string],
  'message' : string,
  'timestamp' : bigint,
}
export interface _SERVICE {
  'deleteCheck' : ActorMethod<[bigint], boolean>,
  'deleteSuggestion' : ActorMethod<[bigint], boolean>,
  'getCheck' : ActorMethod<[bigint], [] | [CheckRecord]>,
  'listChecks' : ActorMethod<[], Array<CheckRecord>>,
  'listSuggestions' : ActorMethod<[], Array<Suggestion>>,
  'saveCheck' : ActorMethod<[string, number, number, string, bigint], bigint>,
  'submitSuggestion' : ActorMethod<[[] | [string], string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];