/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CheckRecord = IDL.Record({
  'id' : IDL.Nat,
  'wordCount' : IDL.Nat,
  'mode' : IDL.Text,
  'text' : IDL.Text,
  'plagiarismScore' : IDL.Float64,
  'timestamp' : IDL.Int,
  'aiScore' : IDL.Float64,
});
export const Suggestion = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'deleteCheck' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteSuggestion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCheck' : IDL.Func([IDL.Nat], [IDL.Opt(CheckRecord)], ['query']),
  'listChecks' : IDL.Func([], [IDL.Vec(CheckRecord)], ['query']),
  'listSuggestions' : IDL.Func([], [IDL.Vec(Suggestion)], ['query']),
  'saveCheck' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'submitSuggestion' : IDL.Func([IDL.Opt(IDL.Text), IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CheckRecord = IDL.Record({
    'id' : IDL.Nat,
    'wordCount' : IDL.Nat,
    'mode' : IDL.Text,
    'text' : IDL.Text,
    'plagiarismScore' : IDL.Float64,
    'timestamp' : IDL.Int,
    'aiScore' : IDL.Float64,
  });
  const Suggestion = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'deleteCheck' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteSuggestion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCheck' : IDL.Func([IDL.Nat], [IDL.Opt(CheckRecord)], ['query']),
    'listChecks' : IDL.Func([], [IDL.Vec(CheckRecord)], ['query']),
    'listSuggestions' : IDL.Func([], [IDL.Vec(Suggestion)], ['query']),
    'saveCheck' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'submitSuggestion' : IDL.Func([IDL.Opt(IDL.Text), IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };